version: 2
jobs:
  build:
    docker:
      - image: selenium/standalone-chrome:3.1.0
    steps:
      - checkout
      - run: sudo apt-get install maven
      - run: mvn dependency:go-offline
         
