version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-node-browsers
    steps:
      - checkout
      - run: sudo apt-get install software-properties-common
      - run: sudo apt-add-repository universe
      - run: sudo apt-get update
      - run: sudo apt-get install maven
      - run: sudo apt-get install maven
      - run: mvn dependency:go-offline
         
